//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookingApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static string About
        {
            get
            {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }

        internal static string AboutApp
        {
            get
            {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }

        internal static string Accommodation
        {
            get
            {
                return ResourceManager.GetString("Accommodation", resourceCulture);
            }
        }

        internal static string CityValid
        {
            get
            {
                return ResourceManager.GetString("CityValid", resourceCulture);
            }
        }

        internal static string DateValid
        {
            get
            {
                return ResourceManager.GetString("DateValid", resourceCulture);
            }
        }

        internal static string CountryValid
        {
            get
            {
                return ResourceManager.GetString("CountryValid", resourceCulture);
            }
        }

        internal static string Accommodations
        {
            get
            {
                return ResourceManager.GetString("Accommodations", resourceCulture);
            }
        }

        internal static string RulesFollowing
        {
            get
            {
                return ResourceManager.GetString("RulesFollowing", resourceCulture);
            }
        }

        internal static string NoReservations
        {
            get
            {
                return ResourceManager.GetString("NoReservations", resourceCulture);
            }
        }
        internal static string NoForums
        {
            get
            {
                return ResourceManager.GetString("NoForums", resourceCulture);
            }
        }

        internal static string NoAccommodations
        {
            get
            {
                return ResourceManager.GetString("NoAccommodations", resourceCulture);
            }
        }
        internal static string NoAccommodationsRate
        {
            get
            {
                return ResourceManager.GetString("NoAccommodationsRate", resourceCulture);
            }
        }

        internal static string NoRates
        {
            get
            {
                return ResourceManager.GetString("NoRates", resourceCulture);
            }
        }
        internal static string AddPicture
        {
            get
            {
                return ResourceManager.GetString("AddPicture", resourceCulture);
            }
        }

        internal static string Back
        {
            get
            {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }

        internal static string AllDates
        {
            get
            {
                return ResourceManager.GetString("AllDates", resourceCulture);
            }
        }

        internal static string HostHas
        {
            get
            {
                return ResourceManager.GetString("HostHas", resourceCulture);
            }
        }
        internal static string GuestHas
        {
            get
            {
                return ResourceManager.GetString("GuestHas", resourceCulture);
            }
        }

        internal static string LanguageBtn
        {
            get
            {
                return ResourceManager.GetString("LanguageBtn", resourceCulture);
            }
        }
        internal static string Language
        {
            get
            {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }

        internal static string Path
        {
            get
            {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }

        internal static string SettingsSuccess
        {
            get
            {
                return ResourceManager.GetString("SettingsSuccess", resourceCulture);
            }
        }

        internal static string SettingsError
        {
            get
            {
                return ResourceManager.GetString("SettingsError", resourceCulture);
            }
        }

        internal static string Adventure
        {
            get
            {
                return ResourceManager.GetString("Adventure", resourceCulture);
            }
        }

        internal static string AllForums
        {
            get
            {
                return ResourceManager.GetString("AllForums", resourceCulture);
            }
        }

        internal static string AllRequests
        {
            get
            {
                return ResourceManager.GetString("AllRequests", resourceCulture);
            }
        }

        internal static string AnywhereAnytime
        {
            get
            {
                return ResourceManager.GetString("AnywhereAnytime", resourceCulture);
            }
        }

        internal static string Level1
        {
            get
            {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }

        internal static string Level2
        {
            get
            {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        internal static string Level3
        {
            get
            {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        internal static string Level4
        {
            get
            {
                return ResourceManager.GetString("Level4", resourceCulture);
            }
        }
        internal static string Level5
        {
            get
            {
                return ResourceManager.GetString("Level5", resourceCulture);
            }
        }

        internal static string EnterAt
        {
            get
            {
                return ResourceManager.GetString("EnterAt", resourceCulture);
            }
        }
        internal static string CancelledRes
        {
            get
            {
                return ResourceManager.GetString("CancelledRes", resourceCulture);
            }
        }

        internal static string Country
        {
            get
            {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }

        internal static string Cancel
        {
            get
            {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        internal static string Delay
        {
            get
            {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }

        internal static string CancelReservation
        {
            get
            {
                return ResourceManager.GetString("CancelReservation", resourceCulture);
            }
        }

        internal static string CancelSuccess
        {
            get
            {
                return ResourceManager.GetString("CancelSuccess", resourceCulture);
            }
        }

        internal static string CancelSure
        {
            get
            {
                return ResourceManager.GetString("CancelSure", resourceCulture);
            }
        }

        internal static string City
        {
            get
            {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }

        internal static string Cleanliness
        {
            get
            {
                return ResourceManager.GetString("Cleanliness", resourceCulture);
            }
        }

        internal static string ClosedMessage
        {
            get
            {
                return ResourceManager.GetString("ClosedMessage", resourceCulture);
            }
        }

        internal static string CloseForum
        {
            get
            {
                return ResourceManager.GetString("CloseForum", resourceCulture);
            }
        }

        internal static string CloseSuccess
        {
            get
            {
                return ResourceManager.GetString("CloseSuccess", resourceCulture);
            }
        }

        internal static string CloseSure
        {
            get
            {
                return ResourceManager.GetString("CloseSure", resourceCulture);
            }
        }

        internal static string Comment
        {
            get
            {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }

        internal static string ConfirmPass
        {
            get
            {
                return ResourceManager.GetString("ConfirmPass", resourceCulture);
            }
        }

        internal static string Continue
        {
            get
            {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }

        internal static string Correctness
        {
            get
            {
                return ResourceManager.GetString("Correctness", resourceCulture);
            }
        }

        internal static string CreatedRes
        {
            get
            {
                return ResourceManager.GetString("CreatedRes", resourceCulture);
            }
        }

        internal static string CreateForum
        {
            get
            {
                return ResourceManager.GetString("CreateForum", resourceCulture);
            }
        }

        internal static string CreateForumSuccess
        {
            get
            {
                return ResourceManager.GetString("CreateForumSuccess", resourceCulture);
            }
        }

        internal static string CreateReport
        {
            get
            {
                return ResourceManager.GetString("CreateReport", resourceCulture);
            }
        }

        internal static string DatesProblem
        {
            get
            {
                return ResourceManager.GetString("DatesProblem", resourceCulture);
            }
        }

        internal static string DayNumber
        {
            get
            {
                return ResourceManager.GetString("DayNumber", resourceCulture);
            }
        }

        internal static string DelayRequest
        {
            get
            {
                return ResourceManager.GetString("DelayRequest", resourceCulture);
            }
        }

        internal static string DelaySuccess
        {
            get
            {
                return ResourceManager.GetString("DelaySuccess", resourceCulture);
            }
        }

        internal static string Details
        {
            get
            {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }

        internal static string Developers
        {
            get
            {
                return ResourceManager.GetString("Developers", resourceCulture);
            }
        }

        internal static string EndDate
        {
            get
            {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }

        internal static string Filter
        {
            get
            {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }

        internal static string Forums
        {
            get
            {
                return ResourceManager.GetString("Forums", resourceCulture);
            }
        }

        internal static string GiveUp
        {
            get
            {
                return ResourceManager.GetString("GiveUp", resourceCulture);
            }
        }

        internal static string GuestNumber
        {
            get
            {
                return ResourceManager.GetString("GuestNumber", resourceCulture);
            }
        }

        internal static string Help
        {
            get
            {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }

        internal static string Home
        {
            get
            {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }

        internal static string HomePage
        {
            get
            {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }

        internal static string Host
        {
            get
            {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }

        internal static string HostComment
        {
            get
            {
                return ResourceManager.GetString("HostComment", resourceCulture);
            }
        }

        internal static string HowCancel
        {
            get
            {
                return ResourceManager.GetString("HowCancel", resourceCulture);
            }
        }

        internal static string HowForum
        {
            get
            {
                return ResourceManager.GetString("HowForum", resourceCulture);
            }
        }

        internal static string HowRate
        {
            get
            {
                return ResourceManager.GetString("HowRate", resourceCulture);
            }
        }

        internal static string HowReservation
        {
            get
            {
                return ResourceManager.GetString("HowReservation", resourceCulture);
            }
        }

        internal static string HowSuperGuest
        {
            get
            {
                return ResourceManager.GetString("HowSuperGuest", resourceCulture);
            }
        }

        internal static string InputProblem
        {
            get
            {
                return ResourceManager.GetString("InputProblem", resourceCulture);
            }
        }

        internal static string Level
        {
            get
            {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }

        internal static string Location
        {
            get
            {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }

        internal static string LoggedIn
        {
            get
            {
                return ResourceManager.GetString("LoggedIn", resourceCulture);
            }
        }

        internal static string LogOut
        {
            get
            {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }

        internal static string MaxGuestNumber
        {
            get
            {
                return ResourceManager.GetString("MaxGuestNumber", resourceCulture);
            }
        }

        internal static string MinDayNumber
        {
            get
            {
                return ResourceManager.GetString("MinDayNumber", resourceCulture);
            }
        }

        internal static string NewPass
        {
            get
            {
                return ResourceManager.GetString("NewPass", resourceCulture);
            }
        }

        internal static string NewUser
        {
            get
            {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }

        internal static string OldPass
        {
            get
            {
                return ResourceManager.GetString("OldPass", resourceCulture);
            }
        }

        internal static string Optional
        {
            get
            {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }

        internal static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        internal static string PasswordChange
        {
            get
            {
                return ResourceManager.GetString("PasswordChange", resourceCulture);
            }
        }

        internal static string PostComment
        {
            get
            {
                return ResourceManager.GetString("PostComment", resourceCulture);
            }
        }

        internal static string ProblemCancel
        {
            get
            {
                return ResourceManager.GetString("ProblemCancel", resourceCulture);
            }
        }

        internal static string Profile
        {
            get
            {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }

        internal static string ProfileSettings
        {
            get
            {
                return ResourceManager.GetString("ProfileSettings", resourceCulture);
            }
        }

        internal static string Rate
        {
            get
            {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }

        internal static string RateAccommodation
        {
            get
            {
                return ResourceManager.GetString("RateAccommodation", resourceCulture);
            }
        }

        internal static string RateButton
        {
            get
            {
                return ResourceManager.GetString("RateButton", resourceCulture);
            }
        }

        internal static string RateProblem
        {
            get
            {
                return ResourceManager.GetString("RateProblem", resourceCulture);
            }
        }

        internal static string RatesByHost
        {
            get
            {
                return ResourceManager.GetString("RatesByHost", resourceCulture);
            }
        }

        internal static string RateSuccess
        {
            get
            {
                return ResourceManager.GetString("RateSuccess", resourceCulture);
            }
        }

        internal static string Recommend
        {
            get
            {
                return ResourceManager.GetString("Recommend", resourceCulture);
            }
        }

        internal static string Recommendation
        {
            get
            {
                return ResourceManager.GetString("Recommendation", resourceCulture);
            }
        }

        internal static string ReportSuccess
        {
            get
            {
                return ResourceManager.GetString("ReportSuccess", resourceCulture);
            }
        }

        internal static string ReportType
        {
            get
            {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }

        internal static string RequestDetails
        {
            get
            {
                return ResourceManager.GetString("RequestDetails", resourceCulture);
            }
        }

        internal static string Requests
        {
            get
            {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }

        internal static string Reservation
        {
            get
            {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }

        internal static string ReservationDetails
        {
            get
            {
                return ResourceManager.GetString("ReservationDetails", resourceCulture);
            }
        }

        internal static string ReservationReport
        {
            get
            {
                return ResourceManager.GetString("ReservationReport", resourceCulture);
            }
        }

        internal static string Reservations
        {
            get
            {
                return ResourceManager.GetString("Reservations", resourceCulture);
            }
        }

        internal static string ReservationSuccess
        {
            get
            {
                return ResourceManager.GetString("ReservationSuccess", resourceCulture);
            }
        }

        internal static string Reserve
        {
            get
            {
                return ResourceManager.GetString("Reserve", resourceCulture);
            }
        }

        internal static string ReviewProblem
        {
            get
            {
                return ResourceManager.GetString("ReviewProblem", resourceCulture);
            }
        }

        internal static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        internal static string Search
        {
            get
            {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }

        internal static string SearchAccommodations
        {
            get
            {
                return ResourceManager.GetString("SearchAccommodations", resourceCulture);
            }
        }

        internal static string SearchForums
        {
            get
            {
                return ResourceManager.GetString("SearchForums", resourceCulture);
            }
        }

        internal static string SelectDates
        {
            get
            {
                return ResourceManager.GetString("SelectDates", resourceCulture);
            }
        }

        internal static string Settings
        {
            get
            {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        internal static string Special
        {
            get
            {
                return ResourceManager.GetString("Special", resourceCulture);
            }
        }

        internal static string StartDate
        {
            get
            {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }

        internal static string TimePeriod
        {
            get
            {
                return ResourceManager.GetString("TimePeriod", resourceCulture);
            }
        }

        internal static string UsernameChange
        {
            get
            {
                return ResourceManager.GetString("UsernameChange", resourceCulture);
            }
        }

        internal static string VeryUseful
        {
            get
            {
                return ResourceManager.GetString("VeryUseful", resourceCulture);
            }
        }

        internal static string ViewForum
        {
            get
            {
                return ResourceManager.GetString("ViewForum", resourceCulture);
            }
        }

        internal static string YourForums
        {
            get
            {
                return ResourceManager.GetString("YourForums", resourceCulture);
            }
        }

        internal static string YourProfile
        {
            get
            {
                return ResourceManager.GetString("YourProfile", resourceCulture);
            }
        }

        public static string AboutWelcomeText
        {
            get
            {
                return ResourceManager.GetString("AboutWelcomeText", resourceCulture);
            }
        }

        public static string AboutDiscoverText
        {
            get
            {
                return ResourceManager.GetString("AboutDiscoverText", resourceCulture);
            }
        }

        public static string AboutOurTeam
        {
            get
            {
                return ResourceManager.GetString("AboutOurTeam", resourceCulture);
            }
        }

        public static string LocationDetails
        {
            get
            {
                return ResourceManager.GetString("LocationDetails", resourceCulture);
            }
        }

        public static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        public static string Type
        {
            get
            {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }

        public static string AnywhereAnytimeDesc
        {
            get
            {
                return ResourceManager.GetString("AnywhereAnytimeDesc", resourceCulture);
            }
        }

        public static string AllForumsDesc
        {
            get
            {
                return ResourceManager.GetString("AllForumsDesc", resourceCulture);
            }
        }

        public static string PleaseChooseDays
        {
            get
            {
                return ResourceManager.GetString("PleaseChooseDays", resourceCulture);
            }
        }

        public static string YouCanChoose
        {
            get
            {
                return ResourceManager.GetString("YouCanChoose", resourceCulture);
            }
        }

        public static string WelcomeAA
        {
            get
            {
                return ResourceManager.GetString("WelcomeAA", resourceCulture);
            }
        }

        public static string TheSystemAA
        {
            get
            {
                return ResourceManager.GetString("TheSystemAA", resourceCulture);
            }
        }

        public static string AfterClosing
        {
            get
            {
                return ResourceManager.GetString("AfterClosing", resourceCulture);
            }
        }

        public static string PleaseChooseDelay
        {
            get
            {
                return ResourceManager.GetString("PleaseChooseDelay", resourceCulture);
            }
        }

        public static string ReservationHelp
        {
            get
            {
                return ResourceManager.GetString("ReservationHelp", resourceCulture);
            }
        }

        public static string CancelHelp
        {
            get
            {
                return ResourceManager.GetString("CancelHelp", resourceCulture);
            }
        }

        public static string RateHelp
        {
            get
            {
                return ResourceManager.GetString("RateHelp", resourceCulture);
            }
        }

        public static string SuperGuestHelp
        {
            get
            {
                return ResourceManager.GetString("SuperGuestHelp", resourceCulture);
            }
        }

        public static string ForumHelp
        {
            get
            {
                return ResourceManager.GetString("ForumHelp", resourceCulture);
            }
        }

        public static string MoreDetailed
        {
            get
            {
                return ResourceManager.GetString("MoreDetailed", resourceCulture);
            }
        }

        public static string FindPerfect
        {
            get
            {
                return ResourceManager.GetString("FindPerfect", resourceCulture);
            }
        }

        public static string PreviousDates
        {
            get
            {
                return ResourceManager.GetString("PreviousDates", resourceCulture);
            }
        }

        public static string NewDates
        {
            get
            {
                return ResourceManager.GetString("NewDates", resourceCulture);
            }
        }

        public static string PeopleNum
        {
            get
            {
                return ResourceManager.GetString("PeopleNum", resourceCulture);
            }
        }

        public static string DayNum
        {
            get
            {
                return ResourceManager.GetString("DayNum", resourceCulture);
            }
        }

        public static string SuperGuestStatus
        {
            get
            {
                return ResourceManager.GetString("SuperGuestStatus", resourceCulture);
            }
        }

        public static string GuestStatus
        {
            get
            {
                return ResourceManager.GetString("GuestStatus", resourceCulture);
            }
        }

        public static string Until
        {
            get
            {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }

        public static string TotalRes
        {
            get
            {
                return ResourceManager.GetString("TotalRes", resourceCulture);
            }
        }

        public static string ResPastYear
        {
            get
            {
                return ResourceManager.GetString("ResPastYear", resourceCulture);
            }
        }

        public static string Rating
        {
            get
            {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }

        public static string CancelHint
        {
            get
            {
                return ResourceManager.GetString("CancelHint", resourceCulture);
            }
        }

        public static string ClosedForum
        {
            get
            {
                return ResourceManager.GetString("ClosedForum", resourceCulture);
            }
        }

        public static string WelcomeRating
        {
            get
            {
                return ResourceManager.GetString("WelcomeRating", resourceCulture);
            }
        }

        public static string OptionalMsg
        {
            get
            {
                return ResourceManager.GetString("OptionalMsg", resourceCulture);
            }
        }

        public static string RateHint
        {
            get
            {
                return ResourceManager.GetString("RateHint", resourceCulture);
            }
        }

        public static string CleanlinessValid
        {
            get
            {
                return ResourceManager.GetString("CleanlinessValid", resourceCulture);
            }
        }

        public static string CorrectnessValid
        {
            get
            {
                return ResourceManager.GetString("CorrectnessValid", resourceCulture);
            }
        }

        public static string CommentValid
        {
            get
            {
                return ResourceManager.GetString("CommentValid", resourceCulture);
            }
        }

        public static string ChooseHint
        {
            get
            {
                return ResourceManager.GetString("ChooseHint", resourceCulture);
            }
        }

        public static string RatesByHostDesc
        {
            get
            {
                return ResourceManager.GetString("RatesByHostDesc", resourceCulture);
            }
        }

        public static string RecommendDesc
        {
            get
            {
                return ResourceManager.GetString("RecommendDesc", resourceCulture);
            }
        }

        public static string LocatedReport
        {
            get
            {
                return ResourceManager.GetString("LocatedReport", resourceCulture);
            }
        }

        public static string RquestsDesc
        {
            get
            {
                return ResourceManager.GetString("RquestsDesc", resourceCulture);
            }
        }

        public static string Pending
        {
            get
            {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }

        public static string Approved
        {
            get
            {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }

        public static string Rejected
        {
            get
            {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }

        public static string WelcomeRes
        {
            get
            {
                return ResourceManager.GetString("WelcomeRes", resourceCulture);
            }
        }

        public static string Required
        {
            get
            {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }

        public static string InputHint
        {
            get
            {
                return ResourceManager.GetString("InputHint", resourceCulture);
            }
        }

        public static string ReportsDesc
        {
            get
            {
                return ResourceManager.GetString("ReportsDesc", resourceCulture);
            }
        }

        public static string BonusPoints
        {
            get
            {
                return ResourceManager.GetString("BonusPoints", resourceCulture);
            }
        }

        public static string DateRangeValid
        {
            get
            {
                return ResourceManager.GetString("DateRangeValid", resourceCulture);
            }
        }

        public static string GuestNumValid
        {
            get
            {
                return ResourceManager.GetString("GuestNumValid", resourceCulture);
            }
        }

        public static string Days
        {
            get
            {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }

        public static string WelcomeHome
        {
            get
            {
                return ResourceManager.GetString("WelcomeHome", resourceCulture);
            }
        }

        public static string Date
        {
            get
            {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
    }
}
